name: authpass
description: Password Manager with support for kdbx 3.x and 4.x
publish_to: none
version: 1.7.12+151

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #  kdbx: ^0.2.0
  kdbx:
    path: ../deps/kdbx.dart
  argon2_ffi: ^1.0.0
  simple_form_field_validator:
    git:
      url: https://github.com/hpoul/flutter_utils.git
      path: packages/simple_form_field_validator
      ref: 4c65f09005a1086525ebe2ae004eccdc2dd56fe1
  logging: ^1.0.0
  logging_appenders: ^1.0.0
  diac_client:
    path: ../deps/diac/diac_client

  synchronized: ^3.0.0
#  file_picker: ^1.6.2
  file_picker_writable: ^2.0.0
  #  file_picker_writable:
#    path: /Users/herbert/dev/file_picker_writable
#  file_picker_writable:
#    git:
#      url: https://github.com/hpoul/file_picker_writable.git
#      ref: fc45c929361d9ace37e5f7b2fae756b98e85b223
  json_annotation: ^4.0.0
  freezed_annotation: ^0.14.0
  built_value: ^8.0.0
  simple_json_persistence: ^2.0.0-nullsafety.4
  provider: ^4.3.2+1
  http: ^0.13.0
  meta: '>=1.0.0 <2.0.0'
  clock: ^1.1.0
  intl: ^0.17.0
  path: ^1.8.0
  isolate: ^2.0.3
#  clipboard_manager: ^0.0.4

  flutter_async_utils: ^0.1.0
  flutter_svg: ">=0.20.0-nullsafety.3 <1.0.0"
  #usage: ^3.4.1
  usage:
    git:
      url: https://github.com/hpoul/usage.git
      ref: custom-user-agent
  package_info: ^2.0.0
#  package_info: ^0.4.0+13
#  package_info_macos:
#    git:
#      url: https://github.com/authpass/package_info_macos.git
##    path: ../deps/package_info_macos
  device_info: ^2.0.0
  path_provider: ^2.0.1
#  path_provider_macos: ^0.0.4+4
#  path_provider_linux: ">=0.0.1 <2.0.0"
  #path_provider_windows: '>=0.0.1+2 <2.0.0'
  analytics_event: ^0.1.2
  autofill_service:
    path: ../deps/autofill_service

  flutter_colorpicker: ^0.3.4
  # flutter_speed_dial: ^1.2.5
  flutter_speed_dial: # overflow -> clipBehavior
    git:
      url: https://github.com/authpass/flutter_speed_dial.git
      ref: 7ad1672e22627d1106151ed8602b52bb99b9a8d2
  flutter_email_sender: ^3.0.1
  flutter_store_listing: ^0.2.0

  biometric_storage: ^2.0.1
#  biometric_storage:
#    path: ../deps/biometric_storage
  uuid: ^3.0.1
  url_launcher: ^6.0.2
  font_awesome_flutter: ^8.8.1
  otp: ^3.0.0-nullsafety.0
  zxcvbn: ^0.0.1


  # UI Utilities and Widgets
  badges: ^1.2.0
  qr_flutter: ^3.2.0
  flushbar: ^1.10.4
  filesystem_picker: ^1.0.2
  tinycolor: ^1.0.3

  # (Small) utility packages
  quiver: ">=3.0.0-nullsafety.3 <4.0.0"
  tuple: ^1.0.3
  rxdart: ^0.26.0
  charcode: ^1.1.3
  recase: ^3.0.0
  # collection utilities:
  flinq: ^1.1.1

  string_literal_finder_annotations: ^0.1.1+1

  # WebDAV
  http_auth: ^0.3.1

  # google drive
  googleapis: ^2.0.0
  googleapis_auth: ^1.0.0

  # dropbox
  #oauth2: ^1.3.0
  oauth2:
    #path: /Users/herbert/dev/patches/oauth2
    git:
      url: https://github.com/authpass/oauth2.git
      ref: 595e5829bd3a36a69999a99473d3aad6fd8febc8

  # FDE
  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 8ea9f1ce79f04e44bd6392f4155a014b0a7eb6e8
#      ref: android-dummy-plugin
#      url: https://github.com/google/flutter-desktop-embedding.git
#      path: plugins/file_chooser

  macos_secure_bookmarks: ^0.1.2+1

  # UI Utils
  percent_indicator: ^2.1.5

  # Plugins
  #flutter_barcode_scanner: ^0.1.7
#  barcode_scan: ^3.0.1 <-- not working (protobuf damnit)
  barcode_scan:
    git:
      url: https://github.com/RohitKumarMishra/flutter_barcode_reader.git
      ref: 85cfc7efee91c3444d24435486cf292a32f04499
  #open_file: ^3.0.3
  open_file:
    git:
      url: https://github.com/mit-mit/open_file.git
      ref: 267da7866fec41377ecf6e2075f63d49413f30ba
  esys_flutter_share: ^1.0.2
  flutter_windowmanager: ^0.0.2

  mime: ^0.9.7
  pedantic: ^1.9.2
  ffi: ^1.0.0
  # AuthPass Cloud email deps
  enough_mail: ^0.3.0
  flutter_html: ^1.2.0
  flutter_linkify: ^3.1.3
#  openapi_base: ^0.1.5+5
  flutter_cache_manager: ^3.0.0-nullsafety.1
  cached_network_image: ^3.0.0-nullsafety
  authpass_cloud_shared:
    path: ../deps/authpass-cloud/packages/authpass_cloud_shared
  # windows updater
  winsparkle_flutter:
    git:
      url: https://github.com/authpass/winsparkle_flutter.git
      ref: 1e124a5056709c00ec05f2c1e3bd8c2084fe962b
  
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
#  test: any
  mockito: ^5.0.4
#   https://github.com/flutter/flutter/issues/62240
#  analyzer: ^0.39.17
  json_serializable: ^4.0.2
  build_runner: ^1.10.2
  builder_static_text: ^0.0.1+2
  built_value_generator: ^8.0.0
  analytics_event_gen: ^0.1.2+1
  freezed: ^0.12.7
  plugin_platform_interface: ^2.0.0

dependency_overrides:
#  pedantic: ^1.9.2
#  build_runner: ^1.10.2
#  xml: '>=3.7.0 <4.0.0'
#  petitparser: '>=3.0.0 <4.0.0'
  kdbx:
    path: ../deps/kdbx.dart
  path_provider: ^2.0.1
  # The following two are required since flutter 1.21
  # but blocked by e.g flutter_cache_manager
#  file: ^6.1.0
#  process: ^4.0.0-nullsafety.1
  intl: ^0.17.0
#  clock: ^1.1.0
  flutter_svg: ">=0.20.0-nullsafety.3 <1.0.0"
#  xml: "^5.0.0-nullsafety.0"
  quiver: ">=3.0.0-nullsafety.3 <4.0.0"
  crypto: ^3.0.0
#  archive: ^3.0.0
#  logging: ^1.0.0-nullsafety
  shelf: ^1.0.0
  analyzer: ^0.41.0 # built_value_generator >=8.0.0-nullsafety.0 depends on analyzer ^0.40.0
#  http: ^0.13.0 # enough_mail >=0.0.30 depends on http ^0.12.2
#  convert: ^3.0.0 # enough_mail >=0.0.34 depends on basic_utils ^2.6.3 which depends on convert ^2.1.1, enough_mail >=0.0.34 requires convert ^2.1.1
#  basic_utils: ^3.0.0-nullsafety.0

#  openapi_base:
#    path: /Users/herbert/dev/authpass-cloud/deps/openapi_dart/packages/openapi_base

#  url_launcher_fde:
#    path: /Users/herbert/dev/flutter/flutter-desktop-embedding/plugins/flutter_plugins/url_launcher_fde
#  file_chooser:
#    path: /Users/herbert/dev/flutter/flutter-desktop-embedding/plugins/file_chooser
#  biometric_storage:
#    path: ../deps/biometric_storage
#  macos_secure_bookmarks:
#    path: /Users/herbert/dev/macos_secure_bookmarks


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/jetbrains/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/jetbrains/JetBrainsMono-Bold.ttf
          weight: 700
